"""Sprite Studio render worker.

Takes a project in phase='render', orchestrates Seedance shot generation,
ElevenLabs narration (conditional on use_narrator), music pick, and ffmpeg
final stitch. Produces final_video_path.

Architecture (P08b-aware):
- Each shot's audio is generated by Seedance natively (has_dialog flag).
- ElevenLabs only produces narrator voice-over, only when use_narrator=True.
- ffmpeg ducks narrator volume during dialog shots (compute_dialog_windows).

Concurrency:
- Up to MAX_SHOT_CONCURRENCY shot renders in flight (default 4).
- Narration runs in parallel with shots (single task).
- Music pick runs as a fast separate sync task.

Resilience:
- One failed shot does not abort the project. Stitch proceeds with N-1
  shots if at least 1 shot + (narration if use_narrator) succeeded.
- On startup, orphan 'running' jobs from prior crashes are marked
  'cancelled' so the worker re-attempts them.
- KeyboardInterrupt / cancellation flag --> mark in-flight jobs cancelled,
  leave project in phase='render' for resume.

Cost guard:
- BUDGET_HARD_LIMIT_USD checked before each paid call.
- Cost mutation is owned by the service clients (seedance.image_to_video and
  elevenlabs.synthesize_narration call db.increment_project_cost).

Progress signaling:
- A per-project ProgressBus publishes ProgressEvent objects.
- /sprite_status reads the latest event for the project via latest_progress().
"""
from __future__ import annotations

import asyncio
import logging
import random
import time
import zipfile
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Optional

from .. import db, env as _env
from ..services import (
    ImageClient,
    MODEL_FAST,
    MODEL_STANDARD,
    VideoClient,
    VoiceClient,
)
from ..services.errors import (
    BudgetExceededError,
    FFmpegError,
    FileInvalidError,
    ProviderContentPolicyError,
    SpriteStudioError,
)
from ..services.ffmpeg_runner import (
    compute_dialog_windows,
    probe,
    stitch_final,
)
from ..models import StylePreset
from ..style_presets import get_preset


logger = logging.getLogger("sprite_studio.workers.render")


# --------------- constants ---------------

MAX_SHOT_CONCURRENCY = 4
MAX_RENDER_MINUTES_DEFAULT = 30
BUDGET_HARD_LIMIT_USD_DEFAULT = 30.0
PARTIAL_OUTPUT_DIRNAME = "_partial"
MUSIC_LIBRARY_ROOT = (
    Path(__file__).resolve().parents[1] / "music_library"
)
PROJECTS_ROOT = (
    Path(__file__).resolve().parents[1] / "projects"
)
SHOT_MIN_DURATION_SECONDS = 0.5


# --------------- progress events ---------------

@dataclass
class ProgressEvent:
    project_id: str
    timestamp: float
    stage: str
    detail: str
    completed: int = 0
    total: int = 0
    error: Optional[str] = None


class ProgressBus:
    """Per-project progress event registry. In-memory.

    Bounded to 200 events per project; older events evicted FIFO. The
    /sprite_status read path returns the most recent event.
    """
    def __init__(self) -> None:
        self._queues: dict[str, asyncio.Queue[ProgressEvent]] = {}
        self._latest: dict[str, ProgressEvent] = {}
        self._lock = asyncio.Lock()

    async def emit(self, event: ProgressEvent) -> None:
        async with self._lock:
            q = self._queues.get(event.project_id)
            if q is None:
                q = asyncio.Queue(maxsize=200)
                self._queues[event.project_id] = q
            if q.full():
                try:
                    q.get_nowait()
                except asyncio.QueueEmpty:
                    pass
            await q.put(event)
            self._latest[event.project_id] = event
        logger.info(
            "progress project=%s stage=%s detail=%s",
            event.project_id, event.stage, event.detail,
        )

    def latest(self, project_id: str) -> Optional[ProgressEvent]:
        return self._latest.get(project_id)

    def clear(self, project_id: str) -> None:
        self._queues.pop(project_id, None)
        self._latest.pop(project_id, None)


PROGRESS_BUS = ProgressBus()


# --------------- cancellation registry ---------------

class CancellationRegistry:
    """In-memory map project_id -> asyncio.Event for cooperative cancellation.

    Process-local. A new process won't see flags from a prior process; it
    relies on the orphan-job sweep at RenderWorker startup instead.
    """
    def __init__(self) -> None:
        self._flags: dict[str, asyncio.Event] = {}
        self._lock = asyncio.Lock()

    async def get_or_create(self, project_id: str) -> asyncio.Event:
        async with self._lock:
            if project_id not in self._flags:
                self._flags[project_id] = asyncio.Event()
            return self._flags[project_id]

    async def signal(self, project_id: str) -> None:
        flag = await self.get_or_create(project_id)
        flag.set()

    def is_cancelled(self, project_id: str) -> bool:
        flag = self._flags.get(project_id)
        return flag is not None and flag.is_set()

    def clear(self, project_id: str) -> None:
        self._flags.pop(project_id, None)


CANCELLATION_REGISTRY = CancellationRegistry()


# --------------- result types ---------------

@dataclass
class ShotResult:
    shot_id: str
    ordinal: int
    success: bool
    video_path: Optional[Path] = None
    duration_seconds: Optional[float] = None
    has_dialog: bool = False
    cost_usd: float = 0.0
    error: Optional[str] = None


@dataclass
class RenderResult:
    project_id: str
    phase: str   # "done" | "failed" | "cancelled"
    final_video_path: Optional[Path] = None
    total_cost_usd: float = 0.0
    shot_success_count: int = 0
    shot_failure_count: int = 0
    error: Optional[str] = None
    partial_zip_path: Optional[Path] = None


# --------------- worker ---------------

class RenderWorker:
    def __init__(
        self,
        *,
        video_client: VideoClient,
        voice_client: VoiceClient,
        image_client: Optional[ImageClient] = None,
        seedance_model: str = MODEL_FAST,
        max_shot_concurrency: int = MAX_SHOT_CONCURRENCY,
        max_render_minutes: int = MAX_RENDER_MINUTES_DEFAULT,
        budget_hard_limit_usd: float = BUDGET_HARD_LIMIT_USD_DEFAULT,
    ) -> None:
        self.video = video_client
        self.voice = voice_client
        self.image = image_client
        self.seedance_model = seedance_model
        self._video_model: str = seedance_model  # resolved per render in render_project
        self.shot_sema = asyncio.Semaphore(max_shot_concurrency)
        self.max_render_seconds = max_render_minutes * 60
        self.budget_limit = budget_hard_limit_usd

    def _resolve_video_model(self) -> str:
        """Resolve Seedance tier from SPRITE_STUDIO_VIDEO_TIER each render.

        Cached on the worker instance for the duration of one render so the
        env can't flip mid-project. Default 'fast' keeps hackathon spend low;
        set 'standard' for production runs.
        """
        tier = _env.get_video_tier()
        return MODEL_STANDARD if tier == "standard" else MODEL_FAST

    # --------- entry point ---------

    async def render_project(self, project_id: str) -> RenderResult:
        """Render a project end-to-end. Returns a RenderResult; never raises
        for normal flow errors. Raises only for programmer mistakes
        (missing project, wrong phase) so the orchestrator catches and
        surfaces a clear error to the user.
        """
        project = db.get_project(project_id)
        if project is None:
            raise OrchestratorRenderError(f"unknown project: {project_id}")

        phase = project["phase"]
        if phase not in ("render", "failed"):
            raise OrchestratorRenderError(
                f"render_project requires phase 'render' or 'failed', got {phase!r}"
            )

        self._sweep_orphan_jobs(project_id)

        if phase == "failed":
            db.update_project(project_id, phase="render", error_message=None)
        else:
            db.update_project(project_id, error_message=None)

        CANCELLATION_REGISTRY.clear(project_id)
        cancel_flag = await CANCELLATION_REGISTRY.get_or_create(project_id)

        tier = _env.get_video_tier()
        self._video_model = self._resolve_video_model()
        logger.info(
            "video tier=%s model=%s project=%s",
            tier, self._video_model, project_id,
        )

        await PROGRESS_BUS.emit(ProgressEvent(
            project_id=project_id,
            timestamp=time.time(),
            stage="queued",
            detail=f"initializing render (tier={tier})",
        ))

        watchdog_task = asyncio.create_task(
            self._watchdog(project_id, cancel_flag)
        )

        try:
            return await self._render_inner(project, cancel_flag)
        except asyncio.CancelledError:
            await self._mark_cancelled(project_id, "render task cancelled")
            return RenderResult(
                project_id=project_id, phase="cancelled",
                error="render task cancelled",
                total_cost_usd=self._fresh_cost(project_id),
            )
        except Exception as e:
            logger.exception("render_project unexpected error project=%s", project_id)
            await self._mark_failed(project_id, f"unexpected error: {e}")
            return RenderResult(
                project_id=project_id, phase="failed",
                error=f"unexpected: {e}",
                total_cost_usd=self._fresh_cost(project_id),
            )
        finally:
            watchdog_task.cancel()
            try:
                await watchdog_task
            except (asyncio.CancelledError, Exception):
                pass

    # --------- inner pipeline ---------

    async def _render_inner(
        self,
        project: dict,
        cancel_flag: asyncio.Event,
    ) -> RenderResult:
        project_id = project["id"]
        shots = db.list_shots(project_id)
        if not shots:
            await self._mark_failed(project_id, "no shots in project")
            return RenderResult(
                project_id=project_id, phase="failed",
                error="no shots in project",
            )

        preset = get_preset(project["style_preset_id"])
        use_narrator = bool(project.get("use_narrator"))
        narrator_script = project.get("narrator_script")

        if self._over_budget(project_id):
            await self._mark_failed(
                project_id,
                f"already over budget limit ${self.budget_limit:.2f}",
            )
            return RenderResult(
                project_id=project_id, phase="failed",
                total_cost_usd=self._fresh_cost(project_id),
                error="budget exceeded before render",
            )

        proj_root = PROJECTS_ROOT / project_id
        (proj_root / "shots").mkdir(parents=True, exist_ok=True)
        (proj_root / "audio").mkdir(parents=True, exist_ok=True)
        (proj_root / "output").mkdir(parents=True, exist_ok=True)

        await PROGRESS_BUS.emit(ProgressEvent(
            project_id=project_id, timestamp=time.time(),
            stage="rendering_shots",
            detail=f"starting {len(shots)} shots + narration + music",
            total=len(shots),
        ))

        shot_tasks = [
            asyncio.create_task(
                self._render_one_shot(project_id, shot, preset, cancel_flag),
                name=f"shot_{shot['ordinal']}",
            )
            for shot in shots
        ]

        narration_task: Optional[asyncio.Task] = None
        if use_narrator and narrator_script:
            narration_task = asyncio.create_task(
                self._synthesize_narration(project_id, narrator_script, cancel_flag),
                name="narration",
            )

        music_task = asyncio.create_task(
            asyncio.to_thread(self._pick_music, preset),
            name="music",
        )

        shot_results: list[ShotResult] = []
        for t in shot_tasks:
            try:
                shot_results.append(await t)
            except asyncio.CancelledError:
                shot_results.append(ShotResult(
                    shot_id="?", ordinal=-1, success=False,
                    error="cancelled",
                ))
            except Exception as e:
                logger.exception("unexpected shot task error")
                shot_results.append(ShotResult(
                    shot_id="?", ordinal=-1, success=False,
                    error=f"unexpected: {e}",
                ))

        narration_path: Optional[Path] = None
        narration_error: Optional[str] = None
        if narration_task is not None:
            try:
                narration_path = await narration_task
            except asyncio.CancelledError:
                narration_error = "cancelled"
            except SpriteStudioError as e:
                narration_error = f"narration: {e}"
                logger.warning("narration failed project=%s: %s", project_id, e)
            except Exception as e:
                narration_error = f"narration unexpected: {e}"
                logger.exception("narration unexpected error project=%s", project_id)

        music_path: Optional[Path] = None
        try:
            music_path = await music_task
        except Exception as e:
            logger.warning(
                "music pick failed project=%s: %s (proceeding without)",
                project_id, e,
            )

        if cancel_flag.is_set():
            await self._mark_cancelled(project_id, "cancelled during asset generation")
            return RenderResult(
                project_id=project_id, phase="cancelled",
                error="cancelled during asset generation",
                total_cost_usd=self._fresh_cost(project_id),
            )

        successful_shots = [r for r in shot_results if r.success]
        failed_shots = [r for r in shot_results if not r.success]

        if not successful_shots:
            await self._mark_failed(
                project_id,
                "all shot renders failed; check generation_jobs for details",
            )
            return RenderResult(
                project_id=project_id, phase="failed",
                shot_failure_count=len(failed_shots),
                error="all shots failed",
                total_cost_usd=self._fresh_cost(project_id),
            )

        if use_narrator and narration_path is None:
            zip_path = self._save_partial_zip(project_id, successful_shots)
            await self._mark_failed(
                project_id,
                f"narration synthesis failed: {narration_error}; "
                f"per-shot MP4s saved to {zip_path.name}",
            )
            return RenderResult(
                project_id=project_id, phase="failed",
                shot_success_count=len(successful_shots),
                shot_failure_count=len(failed_shots),
                error=f"narration failed: {narration_error}",
                partial_zip_path=zip_path,
                total_cost_usd=self._fresh_cost(project_id),
            )

        await PROGRESS_BUS.emit(ProgressEvent(
            project_id=project_id, timestamp=time.time(),
            stage="stitching",
            detail=(
                f"stitching {len(successful_shots)} shots"
                + (" + narration" if narration_path else "")
                + (" + music" if music_path else "")
            ),
        ))

        ordered = sorted(successful_shots, key=lambda r: r.ordinal)
        shot_paths = [r.video_path for r in ordered]

        # Look up transition_to_next per surviving shot from the DB rows.
        # When a mid-list shot fails its transition is dropped along with
        # it; the previous surviving shot's transition still describes how
        # IT joins to the next-promoted shot, which is the right behavior.
        transition_by_id = {
            s["id"]: s.get("transition_to_next") or "cut" for s in shots
        }
        transitions = [
            transition_by_id.get(r.shot_id, "cut") for r in ordered
        ]

        # Recompute dialog windows on the post-failure timeline so the ducking
        # offsets line up with the actual stitched output, not the original
        # plan that included the failed shot's duration. Transition kinds
        # also feed in so fade overlaps shrink the cursor correctly.
        shots_meta_for_windows = [
            {
                "duration_seconds": r.duration_seconds or 0,
                "has_dialog": r.has_dialog,
                "transition_to_next": transitions[i],
            }
            for i, r in enumerate(ordered)
        ]
        dialog_windows = compute_dialog_windows(shots_meta_for_windows)

        final_path = proj_root / "output" / "final.mp4"

        try:
            await asyncio.to_thread(
                stitch_final,
                shots=shot_paths,
                narration=narration_path,
                music=music_path,
                title_card=None,
                end_card=None,
                output=final_path,
                dialog_windows=dialog_windows,
                transitions=transitions,
            )
        except (FFmpegError, FileInvalidError, OSError, ValueError) as e:
            zip_path = self._save_partial_zip(project_id, successful_shots)
            await self._mark_failed(
                project_id,
                f"ffmpeg stitch failed: {e}; "
                f"per-shot MP4s saved to {zip_path.name}",
            )
            return RenderResult(
                project_id=project_id, phase="failed",
                shot_success_count=len(successful_shots),
                shot_failure_count=len(failed_shots),
                error=f"stitch: {e}",
                partial_zip_path=zip_path,
                total_cost_usd=self._fresh_cost(project_id),
            )

        await PROGRESS_BUS.emit(ProgressEvent(
            project_id=project_id, timestamp=time.time(),
            stage="validating",
            detail="ffprobe final output",
        ))

        try:
            info = await asyncio.to_thread(probe, final_path)
            video_streams = [
                s for s in info.get("streams", []) if s.get("codec_type") == "video"
            ]
            audio_streams = [
                s for s in info.get("streams", []) if s.get("codec_type") == "audio"
            ]
            if not video_streams:
                raise FFmpegError("final output has no video stream")
            if not audio_streams:
                raise FFmpegError("final output has no audio stream")
            duration = float(info.get("format", {}).get("duration", 0))
            if duration < 1.0:
                raise FFmpegError(f"final output suspiciously short: {duration}s")
        except (FFmpegError, FileInvalidError) as e:
            await self._mark_failed(
                project_id,
                f"final output validation failed: {e}",
            )
            return RenderResult(
                project_id=project_id, phase="failed",
                shot_success_count=len(successful_shots),
                shot_failure_count=len(failed_shots),
                error=f"validation: {e}",
                total_cost_usd=self._fresh_cost(project_id),
            )

        ts = db.now_ts()
        db.update_project(
            project_id,
            phase="done",
            final_video_path=str(final_path),
            music_track_path=str(music_path) if music_path else None,
            rendered_at=ts,
            error_message=None,
        )

        cost = self._fresh_cost(project_id)
        await PROGRESS_BUS.emit(ProgressEvent(
            project_id=project_id, timestamp=time.time(),
            stage="done",
            detail=f"final={final_path.name} cost=${cost:.4f}",
        ))

        return RenderResult(
            project_id=project_id, phase="done",
            final_video_path=final_path,
            shot_success_count=len(successful_shots),
            shot_failure_count=len(failed_shots),
            total_cost_usd=cost,
        )

    # --------- per-shot render ---------

    async def _render_one_shot(
        self,
        project_id: str,
        shot: dict,
        preset: StylePreset,
        cancel_flag: asyncio.Event,
    ) -> ShotResult:
        ord_n = shot["ordinal"]
        shot_id = shot["id"]

        # Resume idempotency: a prior run may have produced a valid MP4 for
        # this shot. Re-validate it via probe; if it still passes, reuse it
        # without re-billing the seedance call.
        existing_path = shot.get("rendered_video_path")
        if (
            existing_path
            and Path(existing_path).exists()
            and Path(existing_path).stat().st_size > 0
        ):
            try:
                info = await asyncio.to_thread(probe, Path(existing_path))
                duration = float(info.get("format", {}).get("duration", 0))
                if duration >= SHOT_MIN_DURATION_SECONDS:
                    logger.info(
                        "shot %d already rendered at %s, skipping",
                        ord_n, existing_path,
                    )
                    return ShotResult(
                        shot_id=shot_id, ordinal=ord_n, success=True,
                        video_path=Path(existing_path),
                        duration_seconds=duration,
                        has_dialog=bool(shot.get("has_dialog")),
                        cost_usd=0.0,
                    )
            except (FFmpegError, FileInvalidError, FileNotFoundError):
                logger.warning(
                    "shot %d existing output failed validation; re-rendering",
                    ord_n,
                )

        async with self.shot_sema:
            if cancel_flag.is_set():
                return ShotResult(
                    shot_id=shot_id, ordinal=ord_n, success=False,
                    error="cancelled before start",
                )

            if self._over_budget(project_id):
                db.update_shot(
                    shot_id,
                    render_status="failed",
                    render_error="budget exceeded before shot start",
                )
                return ShotResult(
                    shot_id=shot_id, ordinal=ord_n, success=False,
                    error="budget exceeded",
                )

            ref_path_str = shot.get("reference_still_path")
            if not ref_path_str or not Path(ref_path_str).exists():
                err = f"reference_still_path missing or not on disk: {ref_path_str}"
                db.update_shot(shot_id, render_status="failed", render_error=err)
                return ShotResult(
                    shot_id=shot_id, ordinal=ord_n, success=False, error=err,
                )

            db.update_shot(shot_id, render_status="rendering", render_error=None)

            shot_dir = PROJECTS_ROOT / project_id / "shots" / shot_id
            shot_dir.mkdir(parents=True, exist_ok=True)

            prompt = self._build_seedance_prompt(shot, preset)
            cost_before = self._fresh_cost(project_id)

            await PROGRESS_BUS.emit(ProgressEvent(
                project_id=project_id, timestamp=time.time(),
                stage="rendering_shots",
                detail=f"shot {ord_n} -> seedance",
            ))

            try:
                video_path = await self.video.image_to_video(
                    model=self._video_model,
                    image=Path(ref_path_str),
                    prompt=prompt,
                    duration=int(shot["duration_seconds"]),
                    resolution="720p",
                    ratio="9:16",
                    save_to=shot_dir,
                    project_id=project_id,
                    has_dialog=bool(shot.get("has_dialog")),
                )
            except ProviderContentPolicyError as e:
                err = f"content_policy: {e.original_message or e}"
                db.update_shot(shot_id, render_status="failed", render_error=err[:500])
                return ShotResult(
                    shot_id=shot_id, ordinal=ord_n, success=False, error=err,
                )
            except SpriteStudioError as e:
                err = f"seedance: {e}"
                db.update_shot(shot_id, render_status="failed", render_error=err[:500])
                logger.warning("shot %d failed: %s", ord_n, err)
                return ShotResult(
                    shot_id=shot_id, ordinal=ord_n, success=False, error=err,
                )
            except OSError as e:
                err = f"disk: {e}"
                db.update_shot(shot_id, render_status="failed", render_error=err[:500])
                return ShotResult(
                    shot_id=shot_id, ordinal=ord_n, success=False, error=err,
                )

            try:
                info = await asyncio.to_thread(probe, video_path)
                duration = float(info.get("format", {}).get("duration", 0))
                if duration < SHOT_MIN_DURATION_SECONDS:
                    raise FFmpegError(f"shot duration too short: {duration}s")
            except (FFmpegError, FileInvalidError) as e:
                err = f"shot validation: {e}"
                db.update_shot(shot_id, render_status="failed", render_error=err[:500])
                return ShotResult(
                    shot_id=shot_id, ordinal=ord_n, success=False, error=err,
                )

            cost_after = self._fresh_cost(project_id)
            cost_delta = max(0.0, cost_after - cost_before)

            db.update_shot(
                shot_id,
                rendered_video_path=str(video_path),
                render_status="done",
                cost_usd=cost_delta,
                render_error=None,
            )

            await PROGRESS_BUS.emit(ProgressEvent(
                project_id=project_id, timestamp=time.time(),
                stage="rendering_shots",
                detail=f"shot {ord_n} done (${cost_delta:.4f})",
                completed=1,
            ))

            return ShotResult(
                shot_id=shot_id, ordinal=ord_n, success=True,
                video_path=video_path,
                duration_seconds=duration,
                has_dialog=bool(shot.get("has_dialog")),
                cost_usd=cost_delta,
            )

    # --------- narration ---------

    async def _synthesize_narration(
        self,
        project_id: str,
        script: str,
        cancel_flag: asyncio.Event,
    ) -> Path:
        if cancel_flag.is_set():
            raise SpriteStudioError("cancelled before narration start")

        if self._over_budget(project_id):
            raise BudgetExceededError(
                f"budget exceeded before narration; limit ${self.budget_limit:.2f}"
            )

        await PROGRESS_BUS.emit(ProgressEvent(
            project_id=project_id, timestamp=time.time(),
            stage="synthesizing_narration",
            detail=f"{len(script)} chars",
        ))

        out_dir = PROJECTS_ROOT / project_id / "audio"
        out_dir.mkdir(parents=True, exist_ok=True)
        return await self.voice.synthesize_narration(
            project_id=project_id,
            narrator_script=script,
            save_to=out_dir,
        )

    # --------- music ---------

    def _pick_music(self, preset: StylePreset) -> Optional[Path]:
        """Pick a random track from music_library/<music_tag>/. Returns None
        if the directory is missing or empty. Sync; safe under to_thread.
        """
        tag = getattr(preset, "music_tag", None) or "default"
        d = MUSIC_LIBRARY_ROOT / tag
        if not d.exists() or not d.is_dir():
            logger.info("music: directory %s not found", d)
            return None
        candidates = sorted(
            list(d.glob("*.mp3")) + list(d.glob("*.wav"))
        )
        if not candidates:
            logger.info("music: no tracks in %s", d)
            return None
        chosen = random.choice(candidates)
        logger.info("music: picked %s", chosen.name)
        return chosen

    # --------- helpers ---------

    def _build_seedance_prompt(self, shot: dict, preset: StylePreset) -> str:
        """Compose the Seedance prompt from action + style preset motion descriptor.

        Dialog is already embedded in shot.action by the timeline writer
        (P08b convention), so the action field is the single source of truth
        for what Seedance should produce.
        """
        motion_descriptor = (getattr(preset, "motion_descriptor", "") or "").strip()
        action = shot["action"].strip()
        camera = (shot.get("camera") or "").strip()

        parts = [action]
        if camera and camera.lower() not in action.lower():
            parts.append(f"Camera: {camera}.")
        if motion_descriptor:
            parts.append(motion_descriptor)
        parts.append(
            "Maintain perfect character consistency with the input reference "
            "image throughout the entire clip. No on-screen text. No watermarks."
        )
        return " ".join(parts)

    def _over_budget(self, project_id: str) -> bool:
        proj = db.get_project(project_id)
        if proj is None:
            return False
        return float(proj.get("total_cost_usd") or 0) >= self.budget_limit

    def _fresh_cost(self, project_id: str) -> float:
        proj = db.get_project(project_id)
        return float(proj.get("total_cost_usd") or 0) if proj else 0.0

    def _sweep_orphan_jobs(self, project_id: str) -> None:
        """Mark any 'running' generation_jobs and 'rendering' shots for this
        project as cancelled / pending. Called at render entry to recover
        from prior crashes where a process died mid-job.
        """
        rows = db.list_jobs(project_id=project_id, status="running")
        for row in rows:
            db.mark_job_cancelled(
                row["id"], reason="orphan from prior crashed run",
            )
            logger.warning(
                "orphan job marked cancelled: %s (project=%s, type=%s)",
                row["id"], project_id, row.get("job_type"),
            )
        for s in db.list_shots(project_id):
            if s.get("render_status") == "rendering":
                db.update_shot(
                    s["id"],
                    render_status="pending",
                    render_error="orphan from prior crashed run",
                )

    def _save_partial_zip(
        self,
        project_id: str,
        results: list[ShotResult],
    ) -> Path:
        partial_dir = PROJECTS_ROOT / project_id / "output" / PARTIAL_OUTPUT_DIRNAME
        partial_dir.mkdir(parents=True, exist_ok=True)
        zip_path = partial_dir / f"shots_{int(time.time())}.zip"
        try:
            with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as z:
                for r in results:
                    if r.video_path and r.video_path.exists():
                        z.write(
                            r.video_path,
                            arcname=f"shot_{r.ordinal:02d}_{r.shot_id}.mp4",
                        )
            logger.info("saved partial zip: %s", zip_path)
        except (OSError, zipfile.BadZipFile) as e:
            logger.error("failed to write partial zip: %s", e)
        return zip_path

    async def _mark_failed(self, project_id: str, error: str) -> None:
        db.update_project(
            project_id, phase="failed", error_message=error[:500],
        )
        await PROGRESS_BUS.emit(ProgressEvent(
            project_id=project_id, timestamp=time.time(),
            stage="failed", detail=error[:200], error=error,
        ))
        logger.error("render failed project=%s: %s", project_id, error)

    async def _mark_cancelled(self, project_id: str, detail: str) -> None:
        # Leave phase='render' so a re-run resumes; error_message documents why.
        db.update_project(
            project_id,
            error_message=f"cancelled: {detail}"[:500],
        )
        for row in db.list_jobs(project_id=project_id, status="running"):
            db.mark_job_cancelled(row["id"], reason="render cancelled by user")
        await PROGRESS_BUS.emit(ProgressEvent(
            project_id=project_id, timestamp=time.time(),
            stage="cancelled", detail=detail,
        ))
        logger.warning("render cancelled project=%s: %s", project_id, detail)

    async def _watchdog(
        self,
        project_id: str,
        cancel_flag: asyncio.Event,
    ) -> None:
        """Set the cancellation flag if render exceeds max_render_seconds."""
        try:
            await asyncio.sleep(self.max_render_seconds)
            if not cancel_flag.is_set():
                logger.warning(
                    "watchdog firing: render exceeded %ds for project %s",
                    self.max_render_seconds, project_id,
                )
                cancel_flag.set()
                await PROGRESS_BUS.emit(ProgressEvent(
                    project_id=project_id, timestamp=time.time(),
                    stage="cancelled",
                    detail=f"watchdog: render exceeded {self.max_render_seconds}s",
                ))
        except asyncio.CancelledError:
            pass


# --------- public API helpers ---------

class OrchestratorRenderError(RuntimeError):
    """Programmer error raised by render_project for unknown / wrong-phase
    projects. The orchestrator catches and surfaces a friendly message;
    this is never raised for in-flight provider failures.
    """


async def cancel_render(project_id: str) -> None:
    """Signal the running render for project_id to cancel cooperatively."""
    await CANCELLATION_REGISTRY.signal(project_id)


def latest_progress(project_id: str) -> Optional[dict]:
    """Read-only view for /sprite_status. Returns dict or None."""
    ev = PROGRESS_BUS.latest(project_id)
    if ev is None:
        return None
    return asdict(ev)
